### PR TITLE
completed script for loading data into postgres

### PR DESCRIPTION
**Pull request by hongmm**
@jase-d @mbbph @ClaySamuelC 
Somewhat slow but I managed to load my postgres properly and my csv is now "only" 6-7 GB

### CODE REVIEW

**Review by jase-d — COMMENTED** [review]
Everything looks pretty good. Honestly, there is a lot of updates so wasn't able to go line for line deeply. One thing I did notice though was all of the commented out code. Is that on purpose?

**Comment by hongmm** [comment]
@jase-d Sorry about that, I left some stuff commented out because I still wanted to try the Sequelize route at some point but I might just move it to a different file for now since it's getting in the way. Let me clean up the code a bit so it is easier to read.

**Review by jase-d — APPROVED** [review]
Ok, really clean style of code. Every time I see this make me want to get into async/await more. I imagine it looks even better when not all spaced apart in this format. Are you happy with end product or still working on it?

**Comment by hongmm** [comment]
More or less, I think I will continue on for now and see if I need to fix it down the line at this point. Want to try to get Cassandra working atleast before revisiting

**Review by jase-d — APPROVED** [review]
Looks great, all changes are really obvious and effective. Noticed both updates to the seeding script that you mentioned earlier, smart move on the url switch. Also, the way you handle the environment variables is inspiring. Overall, wouldn't change a thing.

**Pull request merged**
